#!/usr/bin/env bash

binary_file="whitelist.spyrosoft.com"

go build && ./$binary_file &

inotifywait --format "%f" -me close_write -q . | while read file
do
	if [[ ! "$file" =~ \.go$ ]]; then continue; fi
	go build && killall $binary_file && echo "File modified: $file. Restarting server." && ./$binary_file &
done

unset binary_file